import { CountryCode } from 'libphonenumber-js';

export interface Country {
  name: string;
  code: CountryCode;
  dialCode: number;
  emoji: string;
}

export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', dialCode: 93, emoji: '🇦🇫' },
  { name: 'Albania', code: 'AL', dialCode: 355, emoji: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', dialCode: 213, emoji: '🇩🇿' },
  { name: 'American Samoa', code: 'AS', dialCode: 1, emoji: '🇦🇸' },
  { name: 'Andorra', code: 'AD', dialCode: 376, emoji: '🇦🇩' },
  { name: 'Angola', code: 'AO', dialCode: 244, emoji: '🇦🇴' },
  { name: 'Anguilla', code: 'AI', dialCode: 1, emoji: '🇦🇮' },
  // { name: 'Antarctica', code: 'AQ', prefix: 672, emoji: '🇦🇶' },
  { name: 'Argentina', code: 'AR', dialCode: 54, emoji: '🇦🇷' },
  { name: 'Armenia', code: 'AM', dialCode: 374, emoji: '🇦🇲' },
  { name: 'Aruba', code: 'AW', dialCode: 297, emoji: '🇦🇼' },
  { name: 'Australia', code: 'AU', dialCode: 61, emoji: '🇦🇺' },
  { name: 'Austria', code: 'AT', dialCode: 43, emoji: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', dialCode: 994, emoji: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', dialCode: 1, emoji: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', dialCode: 973, emoji: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', dialCode: 880, emoji: '🇧🇩' },
  { name: 'Barbados', code: 'BB', dialCode: 1, emoji: '🇧🇧' },
  { name: 'Belarus', code: 'BY', dialCode: 375, emoji: '🇧🇾' },
  { name: 'Belgium', code: 'BE', dialCode: 32, emoji: '🇧🇪' },
  { name: 'Belize', code: 'BZ', dialCode: 501, emoji: '🇧🇿' },
  { name: 'Benin', code: 'BJ', dialCode: 229, emoji: '🇧🇯' },
  { name: 'Bermuda', code: 'BM', dialCode: 1, emoji: '🇧🇲' },
  { name: 'Bhutan', code: 'BT', dialCode: 975, emoji: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', dialCode: 591, emoji: '🇧🇴' },
  { name: 'Botswana', code: 'BW', dialCode: 267, emoji: '🇧🇼' },
  // { name: 'Bouvet Island', code: 'BV', prefix: 55, emoji: '🇧🇻' },
  { name: 'Brazil', code: 'BR', dialCode: 55, emoji: '🇧🇷' },
  { name: 'British Indian Ocean Territory', code: 'IO', dialCode: 246, emoji: '🇮🇴' },
  { name: 'Bulgaria', code: 'BG', dialCode: 359, emoji: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', dialCode: 226, emoji: '🇧🇫' },
  { name: 'Burundi', code: 'BI', dialCode: 257, emoji: '🇧🇮' },
  { name: 'Cambodia', code: 'KH', dialCode: 855, emoji: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', dialCode: 237, emoji: '🇨🇲' },
  { name: 'Canada', code: 'CA', dialCode: 1, emoji: '🇨🇦' },
  { name: 'Cape Verde', code: 'CV', dialCode: 238, emoji: '🇨🇻' },
  { name: 'Cayman Islands', code: 'KY', dialCode: 1, emoji: '🇰🇾' },
  { name: 'Central African Republic', code: 'CF', dialCode: 236, emoji: '🇨🇫' },
  { name: 'Chad', code: 'TD', dialCode: 235, emoji: '🇹🇩' },
  { name: 'Chile', code: 'CL', dialCode: 56, emoji: '🇨🇱' },
  { name: 'China', code: 'CN', dialCode: 86, emoji: '🇨🇳' },
  { name: 'Christmas Island', code: 'CX', dialCode: 61, emoji: '🇨🇽' },
  { name: 'Colombia', code: 'CO', dialCode: 57, emoji: '🇨🇴' },
  { name: 'Comoros', code: 'KM', dialCode: 269, emoji: '🇰🇲' },
  { name: 'Cook Islands', code: 'CK', dialCode: 682, emoji: '🇨🇰' },
  { name: 'Costa Rica', code: 'CR', dialCode: 506, emoji: '🇨🇷' },
  { name: 'Cuba', code: 'CU', dialCode: 53, emoji: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', dialCode: 357, emoji: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', dialCode: 420, emoji: '🇨🇿' },
  { name: 'Denmark', code: 'DK', dialCode: 45, emoji: '🇩🇰' },
  { name: 'Djibouti', code: 'DJ', dialCode: 253, emoji: '🇩🇯' },
  { name: 'Dominica', code: 'DM', dialCode: 1, emoji: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', dialCode: 1, emoji: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', dialCode: 593, emoji: '🇪🇨' },
  { name: 'Egypt', code: 'EG', dialCode: 20, emoji: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', dialCode: 503, emoji: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GQ', dialCode: 240, emoji: '🇬🇶' },
  { name: 'Eritrea', code: 'ER', dialCode: 291, emoji: '🇪🇷' },
  { name: 'Estonia', code: 'EE', dialCode: 372, emoji: '🇪🇪' },
  { name: 'Ethiopia', code: 'ET', dialCode: 251, emoji: '🇪🇹' },
  { name: 'Faroe Islands', code: 'FO', dialCode: 298, emoji: '🇫🇴' },
  { name: 'Fiji', code: 'FJ', dialCode: 679, emoji: '🇫🇯' },
  { name: 'Finland', code: 'FI', dialCode: 358, emoji: '🇫🇮' },
  { name: 'France', code: 'FR', dialCode: 33, emoji: '🇫🇷' },
  { name: 'French Guiana', code: 'GF', dialCode: 594, emoji: '🇬🇫' },
  { name: 'French Polynesia', code: 'PF', dialCode: 689, emoji: '🇵🇫' },
  // { name: 'French Southern Territories', code: 'TF', prefix: 262, emoji: '🇹🇫' },
  { name: 'Gabon', code: 'GA', dialCode: 241, emoji: '🇬🇦' },
  { name: 'Gambia', code: 'GM', dialCode: 220, emoji: '🇬🇲' },
  { name: 'Georgia', code: 'GE', dialCode: 995, emoji: '🇬🇪' },
  { name: 'Germany', code: 'DE', dialCode: 49, emoji: '🇩🇪' },
  { name: 'Ghana', code: 'GH', dialCode: 233, emoji: '🇬🇭' },
  { name: 'Gibraltar', code: 'GI', dialCode: 350, emoji: '🇬🇮' },
  { name: 'Greece', code: 'GR', dialCode: 30, emoji: '🇬🇷' },
  { name: 'Greenland', code: 'GL', dialCode: 299, emoji: '🇬🇱' },
  { name: 'Grenada', code: 'GD', dialCode: 1, emoji: '🇬🇩' },
  { name: 'Guadeloupe', code: 'GP', dialCode: 590, emoji: '🇬🇵' },
  { name: 'Guam', code: 'GU', dialCode: 1, emoji: '🇬🇺' },
  { name: 'Guatemala', code: 'GT', dialCode: 502, emoji: '🇬🇹' },
  { name: 'Guinea', code: 'GN', dialCode: 224, emoji: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'GW', dialCode: 245, emoji: '🇬🇼' },
  { name: 'Guyana', code: 'GY', dialCode: 592, emoji: '🇬🇾' },
  { name: 'Haiti', code: 'HT', dialCode: 509, emoji: '🇭🇹' },
  { name: 'Honduras', code: 'HN', dialCode: 504, emoji: '🇭🇳' },
  { name: 'Hong Kong', code: 'HK', dialCode: 852, emoji: '🇭🇰' },
  { name: 'Hungary', code: 'HU', dialCode: 36, emoji: '🇭🇺' },
  { name: 'Iceland', code: 'IS', dialCode: 354, emoji: '🇮🇸' },
  { name: 'India', code: 'IN', dialCode: 91, emoji: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', dialCode: 62, emoji: '🇮🇩' },
  { name: 'Iraq', code: 'IQ', dialCode: 964, emoji: '🇮🇶' },
  { name: 'Ireland', code: 'IE', dialCode: 353, emoji: '🇮🇪' },
  { name: 'Israel', code: 'IL', dialCode: 972, emoji: '🇮🇱' },
  { name: 'Italy', code: 'IT', dialCode: 39, emoji: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', dialCode: 1, emoji: '🇯🇲' },
  { name: 'Japan', code: 'JP', dialCode: 81, emoji: '🇯🇵' },
  { name: 'Jordan', code: 'JO', dialCode: 962, emoji: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', dialCode: 7, emoji: '🇰🇿' },
  { name: 'Kenya', code: 'KE', dialCode: 254, emoji: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', dialCode: 686, emoji: '🇰🇮' },
  { name: 'South Korea', code: 'KR', dialCode: 82, emoji: '🇰🇷' },
  { name: 'Kuwait', code: 'KW', dialCode: 965, emoji: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', dialCode: 996, emoji: '🇰🇬' },
  { name: 'Latvia', code: 'LV', dialCode: 371, emoji: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', dialCode: 961, emoji: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', dialCode: 266, emoji: '🇱🇸' },
  { name: 'Liberia', code: 'LR', dialCode: 231, emoji: '🇱🇷' },
  { name: 'Liechtenstein', code: 'LI', dialCode: 423, emoji: '🇱🇮' },
  { name: 'Lithuania', code: 'LT', dialCode: 370, emoji: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', dialCode: 352, emoji: '🇱🇺' },
  { name: 'Macau', code: 'MO', dialCode: 853, emoji: '🇲🇴' },
  { name: 'Madagascar', code: 'MG', dialCode: 261, emoji: '🇲🇬' },
  { name: 'Malawi', code: 'MW', dialCode: 265, emoji: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', dialCode: 60, emoji: '🇲🇾' },
  { name: 'Maldives', code: 'MV', dialCode: 960, emoji: '🇲🇻' },
  { name: 'Mali', code: 'ML', dialCode: 223, emoji: '🇲🇱' },
  { name: 'Malta', code: 'MT', dialCode: 356, emoji: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MH', dialCode: 692, emoji: '🇲🇭' },
  { name: 'Martinique', code: 'MQ', dialCode: 596, emoji: '🇲🇶' },
  { name: 'Mauritania', code: 'MR', dialCode: 222, emoji: '🇲🇷' },
  { name: 'Mauritius', code: 'MU', dialCode: 230, emoji: '🇲🇺' },
  { name: 'Mayotte', code: 'YT', dialCode: 262, emoji: '🇾🇹' },
  { name: 'Mexico', code: 'MX', dialCode: 52, emoji: '🇲🇽' },
  { name: 'Monaco', code: 'MC', dialCode: 377, emoji: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', dialCode: 976, emoji: '🇲🇳' },
  { name: 'Montserrat', code: 'MS', dialCode: 1, emoji: '🇲🇸' },
  { name: 'Morocco', code: 'MA', dialCode: 212, emoji: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', dialCode: 258, emoji: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', dialCode: 95, emoji: '🇲🇲' },
  { name: 'Namibia', code: 'NA', dialCode: 264, emoji: '🇳🇦' },
  { name: 'Nauru', code: 'NR', dialCode: 674, emoji: '🇳🇷' },
  { name: 'Nepal', code: 'NP', dialCode: 977, emoji: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', dialCode: 31, emoji: '🇳🇱' },
  { name: 'New Caledonia', code: 'NC', dialCode: 687, emoji: '🇳🇨' },
  { name: 'New Zealand', code: 'NZ', dialCode: 64, emoji: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', dialCode: 505, emoji: '🇳🇮' },
  { name: 'Niger', code: 'NE', dialCode: 227, emoji: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', dialCode: 234, emoji: '🇳🇬' },
  { name: 'Niue', code: 'NU', dialCode: 683, emoji: '🇳🇺' },
  { name: 'Norfolk Island', code: 'NF', dialCode: 672, emoji: '🇳🇫' },
  { name: 'Northern Mariana Islands', code: 'MP', dialCode: 1, emoji: '🇲🇵' },
  { name: 'Norway', code: 'NO', dialCode: 47, emoji: '🇳🇴' },
  { name: 'Oman', code: 'OM', dialCode: 968, emoji: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', dialCode: 92, emoji: '🇵🇰' },
  { name: 'Palau', code: 'PW', dialCode: 680, emoji: '🇵🇼' },
  { name: 'Panama', code: 'PA', dialCode: 507, emoji: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', dialCode: 675, emoji: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', dialCode: 595, emoji: '🇵🇾' },
  { name: 'Peru', code: 'PE', dialCode: 51, emoji: '🇵🇪' },
  { name: 'Philippines', code: 'PH', dialCode: 63, emoji: '🇵🇭' },
  { name: 'Poland', code: 'PL', dialCode: 48, emoji: '🇵🇱' },
  { name: 'Portugal', code: 'PT', dialCode: 351, emoji: '🇵🇹' },
  { name: 'Puerto Rico', code: 'PR', dialCode: 1, emoji: '🇵🇷' },
  { name: 'Qatar', code: 'QA', dialCode: 974, emoji: '🇶🇦' },
  { name: 'Romania', code: 'RO', dialCode: 40, emoji: '🇷🇴' },
  { name: 'Russia', code: 'RU', dialCode: 7, emoji: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', dialCode: 250, emoji: '🇷🇼' },
  { name: 'Samoa', code: 'WS', dialCode: 685, emoji: '🇼🇸' },
  { name: 'San Marino', code: 'SM', dialCode: 378, emoji: '🇸🇲' },
  { name: 'Saudi Arabia', code: 'SA', dialCode: 966, emoji: '🇸🇦' },
  { name: 'Senegal', code: 'SN', dialCode: 221, emoji: '🇸🇳' },
  { name: 'Seychelles', code: 'SC', dialCode: 248, emoji: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SL', dialCode: 232, emoji: '🇸🇱' },
  { name: 'Singapore', code: 'SG', dialCode: 65, emoji: '🇸🇬' },
  { name: 'Slovakia', code: 'SK', dialCode: 421, emoji: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', dialCode: 386, emoji: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', dialCode: 677, emoji: '🇸🇧' },
  { name: 'Somalia', code: 'SO', dialCode: 252, emoji: '🇸🇴' },
  { name: 'South Africa', code: 'ZA', dialCode: 27, emoji: '🇿🇦' },
  { name: 'Spain', code: 'ES', dialCode: 34, emoji: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', dialCode: 94, emoji: '🇱🇰' },
  { name: 'Sudan', code: 'SD', dialCode: 249, emoji: '🇸🇩' },
  { name: 'Suriname', code: 'SR', dialCode: 597, emoji: '🇸🇷' },
  { name: 'Swaziland', code: 'SZ', dialCode: 268, emoji: '🇸🇿' },
  { name: 'Sweden', code: 'SE', dialCode: 46, emoji: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', dialCode: 41, emoji: '🇨🇭' },
  { name: 'Taiwan', code: 'TW', dialCode: 886, emoji: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', dialCode: 992, emoji: '🇹🇯' },
  { name: 'Thailand', code: 'TH', dialCode: 66, emoji: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TL', dialCode: 670, emoji: '🇹🇱' },
  { name: 'Togo', code: 'TG', dialCode: 228, emoji: '🇹🇬' },
  { name: 'Tokelau', code: 'TK', dialCode: 690, emoji: '🇹🇰' },
  { name: 'Tonga', code: 'TO', dialCode: 676, emoji: '🇹🇴' },
  { name: 'Tunisia', code: 'TN', dialCode: 216, emoji: '🇹🇳' },
  { name: 'Turkey', code: 'TR', dialCode: 90, emoji: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', dialCode: 993, emoji: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', dialCode: 688, emoji: '🇹🇻' },
  { name: 'Uganda', code: 'UG', dialCode: 256, emoji: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', dialCode: 380, emoji: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', dialCode: 971, emoji: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', dialCode: 44, emoji: '🇬🇧' },
  { name: 'United States', code: 'US', dialCode: 1, emoji: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', dialCode: 598, emoji: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', dialCode: 998, emoji: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', dialCode: 678, emoji: '🇻🇺' },
  { name: 'Venezuela', code: 'VE', dialCode: 58, emoji: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', dialCode: 84, emoji: '🇻🇳' },
  { name: 'Western Sahara', code: 'EH', dialCode: 212, emoji: '🇪🇭' },
  { name: 'Yemen', code: 'YE', dialCode: 967, emoji: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', dialCode: 260, emoji: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', dialCode: 263, emoji: '🇿🇼' }
];
