import { CountryCode } from 'libphonenumber-js';

export interface Country {
  name: string;
  code: CountryCode;
  prefix: number;
  emoji: string;
}

export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', prefix: 93, emoji: '🇦🇫' },
  { name: 'Albania', code: 'AL', prefix: 355, emoji: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', prefix: 213, emoji: '🇩🇿' },
  { name: 'American Samoa', code: 'AS', prefix: 1, emoji: '🇦🇸' },
  { name: 'Andorra', code: 'AD', prefix: 376, emoji: '🇦🇩' },
  { name: 'Angola', code: 'AO', prefix: 244, emoji: '🇦🇴' },
  { name: 'Anguilla', code: 'AI', prefix: 1, emoji: '🇦🇮' },
  // { name: 'Antarctica', code: 'AQ', prefix: 672, emoji: '🇦🇶' },
  { name: 'Argentina', code: 'AR', prefix: 54, emoji: '🇦🇷' },
  { name: 'Armenia', code: 'AM', prefix: 374, emoji: '🇦🇲' },
  { name: 'Aruba', code: 'AW', prefix: 297, emoji: '🇦🇼' },
  { name: 'Australia', code: 'AU', prefix: 61, emoji: '🇦🇺' },
  { name: 'Austria', code: 'AT', prefix: 43, emoji: '🇦🇹' },
  { name: 'Azerbaijan', code: 'AZ', prefix: 994, emoji: '🇦🇿' },
  { name: 'Bahamas', code: 'BS', prefix: 1, emoji: '🇧🇸' },
  { name: 'Bahrain', code: 'BH', prefix: 973, emoji: '🇧🇭' },
  { name: 'Bangladesh', code: 'BD', prefix: 880, emoji: '🇧🇩' },
  { name: 'Barbados', code: 'BB', prefix: 1, emoji: '🇧🇧' },
  { name: 'Belarus', code: 'BY', prefix: 375, emoji: '🇧🇾' },
  { name: 'Belgium', code: 'BE', prefix: 32, emoji: '🇧🇪' },
  { name: 'Belize', code: 'BZ', prefix: 501, emoji: '🇧🇿' },
  { name: 'Benin', code: 'BJ', prefix: 229, emoji: '🇧🇯' },
  { name: 'Bermuda', code: 'BM', prefix: 1, emoji: '🇧🇲' },
  { name: 'Bhutan', code: 'BT', prefix: 975, emoji: '🇧🇹' },
  { name: 'Bolivia', code: 'BO', prefix: 591, emoji: '🇧🇴' },
  { name: 'Botswana', code: 'BW', prefix: 267, emoji: '🇧🇼' },
  // { name: 'Bouvet Island', code: 'BV', prefix: 55, emoji: '🇧🇻' },
  { name: 'Brazil', code: 'BR', prefix: 55, emoji: '🇧🇷' },
  { name: 'British Indian Ocean Territory', code: 'IO', prefix: 246, emoji: '🇮🇴' },
  { name: 'Bulgaria', code: 'BG', prefix: 359, emoji: '🇧🇬' },
  { name: 'Burkina Faso', code: 'BF', prefix: 226, emoji: '🇧🇫' },
  { name: 'Burundi', code: 'BI', prefix: 257, emoji: '🇧🇮' },
  { name: 'Cambodia', code: 'KH', prefix: 855, emoji: '🇰🇭' },
  { name: 'Cameroon', code: 'CM', prefix: 237, emoji: '🇨🇲' },
  { name: 'Canada', code: 'CA', prefix: 1, emoji: '🇨🇦' },
  { name: 'Cape Verde', code: 'CV', prefix: 238, emoji: '🇨🇻' },
  { name: 'Cayman Islands', code: 'KY', prefix: 1, emoji: '🇰🇾' },
  { name: 'Central African Republic', code: 'CF', prefix: 236, emoji: '🇨🇫' },
  { name: 'Chad', code: 'TD', prefix: 235, emoji: '🇹🇩' },
  { name: 'Chile', code: 'CL', prefix: 56, emoji: '🇨🇱' },
  { name: 'China', code: 'CN', prefix: 86, emoji: '🇨🇳' },
  { name: 'Christmas Island', code: 'CX', prefix: 61, emoji: '🇨🇽' },
  { name: 'Colombia', code: 'CO', prefix: 57, emoji: '🇨🇴' },
  { name: 'Comoros', code: 'KM', prefix: 269, emoji: '🇰🇲' },
  { name: 'Cook Islands', code: 'CK', prefix: 682, emoji: '🇨🇰' },
  { name: 'Costa Rica', code: 'CR', prefix: 506, emoji: '🇨🇷' },
  { name: 'Cuba', code: 'CU', prefix: 53, emoji: '🇨🇺' },
  { name: 'Cyprus', code: 'CY', prefix: 357, emoji: '🇨🇾' },
  { name: 'Czech Republic', code: 'CZ', prefix: 420, emoji: '🇨🇿' },
  { name: 'Denmark', code: 'DK', prefix: 45, emoji: '🇩🇰' },
  { name: 'Djibouti', code: 'DJ', prefix: 253, emoji: '🇩🇯' },
  { name: 'Dominica', code: 'DM', prefix: 1, emoji: '🇩🇲' },
  { name: 'Dominican Republic', code: 'DO', prefix: 1, emoji: '🇩🇴' },
  { name: 'Ecuador', code: 'EC', prefix: 593, emoji: '🇪🇨' },
  { name: 'Egypt', code: 'EG', prefix: 20, emoji: '🇪🇬' },
  { name: 'El Salvador', code: 'SV', prefix: 503, emoji: '🇸🇻' },
  { name: 'Equatorial Guinea', code: 'GQ', prefix: 240, emoji: '🇬🇶' },
  { name: 'Eritrea', code: 'ER', prefix: 291, emoji: '🇪🇷' },
  { name: 'Estonia', code: 'EE', prefix: 372, emoji: '🇪🇪' },
  { name: 'Ethiopia', code: 'ET', prefix: 251, emoji: '🇪🇹' },
  { name: 'Faroe Islands', code: 'FO', prefix: 298, emoji: '🇫🇴' },
  { name: 'Fiji', code: 'FJ', prefix: 679, emoji: '🇫🇯' },
  { name: 'Finland', code: 'FI', prefix: 358, emoji: '🇫🇮' },
  { name: 'France', code: 'FR', prefix: 33, emoji: '🇫🇷' },
  { name: 'French Guiana', code: 'GF', prefix: 594, emoji: '🇬🇫' },
  { name: 'French Polynesia', code: 'PF', prefix: 689, emoji: '🇵🇫' },
  // { name: 'French Southern Territories', code: 'TF', prefix: 262, emoji: '🇹🇫' },
  { name: 'Gabon', code: 'GA', prefix: 241, emoji: '🇬🇦' },
  { name: 'Gambia', code: 'GM', prefix: 220, emoji: '🇬🇲' },
  { name: 'Georgia', code: 'GE', prefix: 995, emoji: '🇬🇪' },
  { name: 'Germany', code: 'DE', prefix: 49, emoji: '🇩🇪' },
  { name: 'Ghana', code: 'GH', prefix: 233, emoji: '🇬🇭' },
  { name: 'Gibraltar', code: 'GI', prefix: 350, emoji: '🇬🇮' },
  { name: 'Greece', code: 'GR', prefix: 30, emoji: '🇬🇷' },
  { name: 'Greenland', code: 'GL', prefix: 299, emoji: '🇬🇱' },
  { name: 'Grenada', code: 'GD', prefix: 1, emoji: '🇬🇩' },
  { name: 'Guadeloupe', code: 'GP', prefix: 590, emoji: '🇬🇵' },
  { name: 'Guam', code: 'GU', prefix: 1, emoji: '🇬🇺' },
  { name: 'Guatemala', code: 'GT', prefix: 502, emoji: '🇬🇹' },
  { name: 'Guinea', code: 'GN', prefix: 224, emoji: '🇬🇳' },
  { name: 'Guinea-Bissau', code: 'GW', prefix: 245, emoji: '🇬🇼' },
  { name: 'Guyana', code: 'GY', prefix: 592, emoji: '🇬🇾' },
  { name: 'Haiti', code: 'HT', prefix: 509, emoji: '🇭🇹' },
  { name: 'Honduras', code: 'HN', prefix: 504, emoji: '🇭🇳' },
  { name: 'Hong Kong', code: 'HK', prefix: 852, emoji: '🇭🇰' },
  { name: 'Hungary', code: 'HU', prefix: 36, emoji: '🇭🇺' },
  { name: 'Iceland', code: 'IS', prefix: 354, emoji: '🇮🇸' },
  { name: 'India', code: 'IN', prefix: 91, emoji: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', prefix: 62, emoji: '🇮🇩' },
  { name: 'Iraq', code: 'IQ', prefix: 964, emoji: '🇮🇶' },
  { name: 'Ireland', code: 'IE', prefix: 353, emoji: '🇮🇪' },
  { name: 'Israel', code: 'IL', prefix: 972, emoji: '🇮🇱' },
  { name: 'Italy', code: 'IT', prefix: 39, emoji: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', prefix: 1, emoji: '🇯🇲' },
  { name: 'Japan', code: 'JP', prefix: 81, emoji: '🇯🇵' },
  { name: 'Jordan', code: 'JO', prefix: 962, emoji: '🇯🇴' },
  { name: 'Kazakhstan', code: 'KZ', prefix: 7, emoji: '🇰🇿' },
  { name: 'Kenya', code: 'KE', prefix: 254, emoji: '🇰🇪' },
  { name: 'Kiribati', code: 'KI', prefix: 686, emoji: '🇰🇮' },
  { name: 'South Korea', code: 'KR', prefix: 82, emoji: '🇰🇷' },
  { name: 'Kuwait', code: 'KW', prefix: 965, emoji: '🇰🇼' },
  { name: 'Kyrgyzstan', code: 'KG', prefix: 996, emoji: '🇰🇬' },
  { name: 'Latvia', code: 'LV', prefix: 371, emoji: '🇱🇻' },
  { name: 'Lebanon', code: 'LB', prefix: 961, emoji: '🇱🇧' },
  { name: 'Lesotho', code: 'LS', prefix: 266, emoji: '🇱🇸' },
  { name: 'Liberia', code: 'LR', prefix: 231, emoji: '🇱🇷' },
  { name: 'Liechtenstein', code: 'LI', prefix: 423, emoji: '🇱🇮' },
  { name: 'Lithuania', code: 'LT', prefix: 370, emoji: '🇱🇹' },
  { name: 'Luxembourg', code: 'LU', prefix: 352, emoji: '🇱🇺' },
  { name: 'Macau', code: 'MO', prefix: 853, emoji: '🇲🇴' },
  { name: 'Madagascar', code: 'MG', prefix: 261, emoji: '🇲🇬' },
  { name: 'Malawi', code: 'MW', prefix: 265, emoji: '🇲🇼' },
  { name: 'Malaysia', code: 'MY', prefix: 60, emoji: '🇲🇾' },
  { name: 'Maldives', code: 'MV', prefix: 960, emoji: '🇲🇻' },
  { name: 'Mali', code: 'ML', prefix: 223, emoji: '🇲🇱' },
  { name: 'Malta', code: 'MT', prefix: 356, emoji: '🇲🇹' },
  { name: 'Marshall Islands', code: 'MH', prefix: 692, emoji: '🇲🇭' },
  { name: 'Martinique', code: 'MQ', prefix: 596, emoji: '🇲🇶' },
  { name: 'Mauritania', code: 'MR', prefix: 222, emoji: '🇲🇷' },
  { name: 'Mauritius', code: 'MU', prefix: 230, emoji: '🇲🇺' },
  { name: 'Mayotte', code: 'YT', prefix: 262, emoji: '🇾🇹' },
  { name: 'Mexico', code: 'MX', prefix: 52, emoji: '🇲🇽' },
  { name: 'Monaco', code: 'MC', prefix: 377, emoji: '🇲🇨' },
  { name: 'Mongolia', code: 'MN', prefix: 976, emoji: '🇲🇳' },
  { name: 'Montserrat', code: 'MS', prefix: 1, emoji: '🇲🇸' },
  { name: 'Morocco', code: 'MA', prefix: 212, emoji: '🇲🇦' },
  { name: 'Mozambique', code: 'MZ', prefix: 258, emoji: '🇲🇿' },
  { name: 'Myanmar', code: 'MM', prefix: 95, emoji: '🇲🇲' },
  { name: 'Namibia', code: 'NA', prefix: 264, emoji: '🇳🇦' },
  { name: 'Nauru', code: 'NR', prefix: 674, emoji: '🇳🇷' },
  { name: 'Nepal', code: 'NP', prefix: 977, emoji: '🇳🇵' },
  { name: 'Netherlands', code: 'NL', prefix: 31, emoji: '🇳🇱' },
  { name: 'New Caledonia', code: 'NC', prefix: 687, emoji: '🇳🇨' },
  { name: 'New Zealand', code: 'NZ', prefix: 64, emoji: '🇳🇿' },
  { name: 'Nicaragua', code: 'NI', prefix: 505, emoji: '🇳🇮' },
  { name: 'Niger', code: 'NE', prefix: 227, emoji: '🇳🇪' },
  { name: 'Nigeria', code: 'NG', prefix: 234, emoji: '🇳🇬' },
  { name: 'Niue', code: 'NU', prefix: 683, emoji: '🇳🇺' },
  { name: 'Norfolk Island', code: 'NF', prefix: 672, emoji: '🇳🇫' },
  { name: 'Northern Mariana Islands', code: 'MP', prefix: 1, emoji: '🇲🇵' },
  { name: 'Norway', code: 'NO', prefix: 47, emoji: '🇳🇴' },
  { name: 'Oman', code: 'OM', prefix: 968, emoji: '🇴🇲' },
  { name: 'Pakistan', code: 'PK', prefix: 92, emoji: '🇵🇰' },
  { name: 'Palau', code: 'PW', prefix: 680, emoji: '🇵🇼' },
  { name: 'Panama', code: 'PA', prefix: 507, emoji: '🇵🇦' },
  { name: 'Papua New Guinea', code: 'PG', prefix: 675, emoji: '🇵🇬' },
  { name: 'Paraguay', code: 'PY', prefix: 595, emoji: '🇵🇾' },
  { name: 'Peru', code: 'PE', prefix: 51, emoji: '🇵🇪' },
  { name: 'Philippines', code: 'PH', prefix: 63, emoji: '🇵🇭' },
  { name: 'Poland', code: 'PL', prefix: 48, emoji: '🇵🇱' },
  { name: 'Portugal', code: 'PT', prefix: 351, emoji: '🇵🇹' },
  { name: 'Puerto Rico', code: 'PR', prefix: 1, emoji: '🇵🇷' },
  { name: 'Qatar', code: 'QA', prefix: 974, emoji: '🇶🇦' },
  { name: 'Romania', code: 'RO', prefix: 40, emoji: '🇷🇴' },
  { name: 'Russia', code: 'RU', prefix: 7, emoji: '🇷🇺' },
  { name: 'Rwanda', code: 'RW', prefix: 250, emoji: '🇷🇼' },
  { name: 'Samoa', code: 'WS', prefix: 685, emoji: '🇼🇸' },
  { name: 'San Marino', code: 'SM', prefix: 378, emoji: '🇸🇲' },
  { name: 'Saudi Arabia', code: 'SA', prefix: 966, emoji: '🇸🇦' },
  { name: 'Senegal', code: 'SN', prefix: 221, emoji: '🇸🇳' },
  { name: 'Seychelles', code: 'SC', prefix: 248, emoji: '🇸🇨' },
  { name: 'Sierra Leone', code: 'SL', prefix: 232, emoji: '🇸🇱' },
  { name: 'Singapore', code: 'SG', prefix: 65, emoji: '🇸🇬' },
  { name: 'Slovakia', code: 'SK', prefix: 421, emoji: '🇸🇰' },
  { name: 'Slovenia', code: 'SI', prefix: 386, emoji: '🇸🇮' },
  { name: 'Solomon Islands', code: 'SB', prefix: 677, emoji: '🇸🇧' },
  { name: 'Somalia', code: 'SO', prefix: 252, emoji: '🇸🇴' },
  { name: 'South Africa', code: 'ZA', prefix: 27, emoji: '🇿🇦' },
  { name: 'Spain', code: 'ES', prefix: 34, emoji: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', prefix: 94, emoji: '🇱🇰' },
  { name: 'Sudan', code: 'SD', prefix: 249, emoji: '🇸🇩' },
  { name: 'Suriname', code: 'SR', prefix: 597, emoji: '🇸🇷' },
  { name: 'Swaziland', code: 'SZ', prefix: 268, emoji: '🇸🇿' },
  { name: 'Sweden', code: 'SE', prefix: 46, emoji: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', prefix: 41, emoji: '🇨🇭' },
  { name: 'Taiwan', code: 'TW', prefix: 886, emoji: '🇹🇼' },
  { name: 'Tajikistan', code: 'TJ', prefix: 992, emoji: '🇹🇯' },
  { name: 'Thailand', code: 'TH', prefix: 66, emoji: '🇹🇭' },
  { name: 'Timor-Leste', code: 'TL', prefix: 670, emoji: '🇹🇱' },
  { name: 'Togo', code: 'TG', prefix: 228, emoji: '🇹🇬' },
  { name: 'Tokelau', code: 'TK', prefix: 690, emoji: '🇹🇰' },
  { name: 'Tonga', code: 'TO', prefix: 676, emoji: '🇹🇴' },
  { name: 'Tunisia', code: 'TN', prefix: 216, emoji: '🇹🇳' },
  { name: 'Turkey', code: 'TR', prefix: 90, emoji: '🇹🇷' },
  { name: 'Turkmenistan', code: 'TM', prefix: 993, emoji: '🇹🇲' },
  { name: 'Tuvalu', code: 'TV', prefix: 688, emoji: '🇹🇻' },
  { name: 'Uganda', code: 'UG', prefix: 256, emoji: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', prefix: 380, emoji: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', prefix: 971, emoji: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', prefix: 44, emoji: '🇬🇧' },
  { name: 'United States', code: 'US', prefix: 1, emoji: '🇺🇸' },
  { name: 'Uruguay', code: 'UY', prefix: 598, emoji: '🇺🇾' },
  { name: 'Uzbekistan', code: 'UZ', prefix: 998, emoji: '🇺🇿' },
  { name: 'Vanuatu', code: 'VU', prefix: 678, emoji: '🇻🇺' },
  { name: 'Venezuela', code: 'VE', prefix: 58, emoji: '🇻🇪' },
  { name: 'Vietnam', code: 'VN', prefix: 84, emoji: '🇻🇳' },
  { name: 'Western Sahara', code: 'EH', prefix: 212, emoji: '🇪🇭' },
  { name: 'Yemen', code: 'YE', prefix: 967, emoji: '🇾🇪' },
  { name: 'Zambia', code: 'ZM', prefix: 260, emoji: '🇿🇲' },
  { name: 'Zimbabwe', code: 'ZW', prefix: 263, emoji: '🇿🇼' }
];
